### ISSUE TITLE
Sửa nội dung footer + logo

### ISSUE THREAD

**Issue by marunaka114** [marunaka114/bongdatv#43]
1)Sửa nội dung footer 
"DESIGN BY W3LAYOUTS" -> "Copyrights sanco442.com"
2)Thay logo mới cho page.

**Comment by otsuki154** [comment]
Okie nhan ticket

**Comment by otsuki154** [comment]
da fix tai https://github.com/marunaka114/bongdatv/pull/44
su phu review nghe chua?

**Comment by marunaka114** [comment]
da review va merge vao develop
