### ISSUE TITLE
Resize video player

### ISSUE THREAD

**Issue by marunaka114** [marunaka114/bongdatv#46]
Hiện tại kích thước video trận đấu quá nhỏ.
Cần chỉnh lại kích thước video lớn hơn, phù hợp với cả PC và smartphone
![match_detail_video_layout](https://user-images.githubusercontent.com/1535164/30027555-6c778d84-91bc-11e7-9950-49803f75e3bf.png)

**Comment by otsuki154** [comment]
Nhận ticket nhóe
